// Code generated by reset generator. DO NOT EDIT.
//go:generate go run ../../cmd/reset

package main

func (s *ExampleStruct) Reset() {
	if s == nil {
		return
	}

	s.ID = 0
	s.Name = ""
	s.Active = false
	s.Data = s.Data[:0]
}
