// Code generated by reset generator. DO NOT EDIT.
//go:generate go run ../../cmd/reset

package resetexamples

func (s *RequestData) Reset() {
	if s == nil {
		return
	}

	s.Method = ""
	s.Path = ""
	clear(s.Headers)
	s.Body = s.Body[:0]
	clear(s.Query)
	clear(s.Params)
	if s.Size != nil {
		*s.Size = 0
	}
	if s.Timeout != nil {
		*s.Timeout = 0
	}
}

func (s *ResponseData) Reset() {
	if s == nil {
		return
	}

	s.StatusCode = 0
	clear(s.Headers)
	s.Body = s.Body[:0]
	if s.Error != nil {
		*s.Error = ""
	}
	if s.Duration != nil {
		*s.Duration = 0.0
	}
	if s.Size != nil {
		*s.Size = 0
	}
	if s.Cached != nil {
		*s.Cached = false
	}
}

func (s *MiddlewareData) Reset() {
	if s == nil {
		return
	}

	s.RequestID = ""
	if s.UserID != nil {
		*s.UserID = ""
	}
	if s.SessionID != nil {
		*s.SessionID = ""
	}
	s.Timestamp = 0
	clear(s.Metadata)
	s.Permissions = s.Permissions[:0]
	s.Roles = s.Roles[:0]
	if s.Authenticated != nil {
		*s.Authenticated = false
	}
}

func (s *HandlerMetrics) Reset() {
	if s == nil {
		return
	}

	s.RequestCount = 0
	s.ErrorCount = 0
	s.ResponseTime = s.ResponseTime[:0]
	clear(s.StatusCodes)
	clear(s.EndpointStats)
	s.ActiveRequests = s.ActiveRequests[:0]
	s.ErrorMessages = s.ErrorMessages[:0]
	if s.LastReset != nil {
		*s.LastReset = 0
	}
	if s.ProcessingTime != nil {
		*s.ProcessingTime = 0.0
	}
}

func (s *SimpleStruct) Reset() {
	if s == nil {
		return
	}

	s.IntField = 0
	s.StringField = ""
	s.BoolField = false
	s.FloatField = 0.0
}

func (s *ComplexStruct) Reset() {
	if s == nil {
		return
	}

	s.IntSlice = s.IntSlice[:0]
	s.StringSlice = s.StringSlice[:0]
	clear(s.IntMap)
	clear(s.StringMap)
	if s.IntPtr != nil {
		*s.IntPtr = 0
	}
	if s.StringPtr != nil {
		*s.StringPtr = ""
	}
	if s.BoolPtr != nil {
		*s.BoolPtr = false
	}
	if s.FloatPtr != nil {
		*s.FloatPtr = 0.0
	}
}

func (s *NestedStruct) Reset() {
	if s == nil {
		return
	}

	if s.Complex != nil {
		s.Complex.Reset()
	}
	if s.Mixed != nil {
		s.Mixed.Reset()
	}
}

func (s *AllTypesStruct) Reset() {
	if s == nil {
		return
	}

	s.IntVal = 0
	s.Int8Val = 0
	s.Int16Val = 0
	s.Int32Val = 0
	s.Int64Val = 0
	s.UintVal = 0
	s.Uint8Val = 0
	s.Uint16Val = 0
	s.Uint32Val = 0
	s.Uint64Val = 0
	s.Float32Val = 0.0
	s.Float64Val = 0.0
	s.StringVal = ""
	s.BoolVal = false
	s.IntSliceVal = s.IntSliceVal[:0]
	s.StringSliceVal = s.StringSliceVal[:0]
	clear(s.IntMapVal)
	clear(s.StringMapVal)
	if s.IntPtrVal != nil {
		*s.IntPtrVal = 0
	}
	if s.StringPtrVal != nil {
		*s.StringPtrVal = ""
	}
	if s.BoolPtrVal != nil {
		*s.BoolPtrVal = false
	}
	if s.FloatPtrVal != nil {
		*s.FloatPtrVal = 0.0
	}
	if s.ComplexPtrVal != nil {
		s.ComplexPtrVal.Reset()
	}
}

func (s *StorageConfig) Reset() {
	if s == nil {
		return
	}

	s.Host = ""
	s.Port = 0
	s.Database = ""
	clear(s.Options)
	if s.Timeout != nil {
		*s.Timeout = 0
	}
	if s.SSL != nil {
		*s.SSL = false
	}
}

func (s *CacheEntry) Reset() {
	if s == nil {
		return
	}

	s.Key = ""
	s.Value = s.Value[:0]
	s.ExpiresAt = 0
	clear(s.Metadata)
	s.Tags = s.Tags[:0]
	if s.HitCount != nil {
		*s.HitCount = 0
	}
}

func (s *ConnectionPool) Reset() {
	if s == nil {
		return
	}

	s.MaxConnections = 0
	s.CurrentCount = 0
	s.Available = s.Available[:0]
	clear(s.InUse)
	if s.Config != nil {
		s.Config.Reset()
	}
	clear(s.Stats)
}

func (s *QueryResult) Reset() {
	if s == nil {
		return
	}

	s.Rows = s.Rows[:0]
	s.Columns = s.Columns[:0]
	if s.RowCount != nil {
		*s.RowCount = 0
	}
	if s.Error != nil {
		*s.Error = ""
	}
	clear(s.Metadata)
	if s.Duration != nil {
		*s.Duration = 0.0
	}
	if s.CacheHit != nil {
		*s.CacheHit = false
	}
}
